table.insert(global_includedirs, "runtime/stb")
table.insert(global_files, "runtime/stb/**.c")
table.insert(global_defines, "STB_IMAGE_WRITE_STATIC=")
table.insert(global_defines, "STBIWDEF=")
table.insert(global_defines, "STB_IMAGE_WRITE_IMPLEMENTATION=")