var searchData=
[
  ['v_5fformatter_0',['v_formatter',['../classspdlog_1_1details_1_1v__formatter.html',1,'spdlog::details']]],
  ['validationlayer_1',['ValidationLayer',['../structluisa_1_1compute_1_1_validation_layer.html',1,'luisa::compute']]],
  ['value_2',['value',['../classdetail_1_1value.html',1,'detail']]],
  ['value_3c_20basic_5fprintf_5fcontext_20_3e_3',['value&lt; basic_printf_context &gt;',['../classdetail_1_1value.html',1,'detail']]],
  ['value_3c_20generic_5fcontext_20_3e_4',['value&lt; generic_context &gt;',['../classdetail_1_1value.html',1,'detail']]],
  ['value_5fcompare_5',['value_compare',['../classeastl_1_1map_1_1value__compare.html',1,'eastl::map&lt; Key, T, Compare, Allocator &gt;::value_compare'],['../classeastl_1_1multimap_1_1value__compare.html',1,'eastl::multimap&lt; Key, T, Compare, Allocator &gt;::value_compare']]],
  ['value_5ftype_6',['value_type',['../structeastl_1_1iterator__traits.html',1,'eastl::value_type&lt; Iterator &gt;'],['../unionmove__only__function__detail_1_1__move__only__pointer_1_1value__type.html',1,'move_only_function_detail::_move_only_pointer::value_type']]],
  ['var_7',['Var',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20bool_20_3e_8',['Var&lt; bool &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20bool2_20_3e_9',['Var&lt; bool2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20bool3_20_3e_10',['Var&lt; bool3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20bool4_20_3e_11',['Var&lt; bool4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20bufferview_3c_20t_20_3e_20_3e_12',['Var&lt; BufferView&lt; T &gt; &gt;',['../structluisa_1_1compute_1_1_var_3_01_buffer_view_3_01_t_01_4_01_4.html',1,'luisa::compute']]],
  ['var_3c_20bytebuffer_20_3e_13',['Var&lt; ByteBuffer &gt;',['../structluisa_1_1compute_1_1_var_3_01_byte_buffer_01_4.html',1,'luisa::compute']]],
  ['var_3c_20float_20_3e_14',['Var&lt; float &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20float2_20_3e_15',['Var&lt; float2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20float2x2_20_3e_16',['Var&lt; float2x2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20float3_20_3e_17',['Var&lt; float3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20float3x3_20_3e_18',['Var&lt; float3x3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20float4_20_3e_19',['Var&lt; float4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20float4x4_20_3e_20',['Var&lt; float4x4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20half_20_3e_21',['Var&lt; half &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20half2_20_3e_22',['Var&lt; half2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20half3_20_3e_23',['Var&lt; half3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20half4_20_3e_24',['Var&lt; half4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20imageview_3c_20t_20_3e_20_3e_25',['Var&lt; ImageView&lt; T &gt; &gt;',['../structluisa_1_1compute_1_1_var_3_01_image_view_3_01_t_01_4_01_4.html',1,'luisa::compute']]],
  ['var_3c_20int_20_3e_26',['Var&lt; int &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20int2_20_3e_27',['Var&lt; int2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20int3_20_3e_28',['Var&lt; int3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20int4_20_3e_29',['Var&lt; int4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20short_20_3e_30',['Var&lt; short &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20short2_20_3e_31',['Var&lt; short2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20short3_20_3e_32',['Var&lt; short3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20short4_20_3e_33',['Var&lt; short4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20slong_20_3e_34',['Var&lt; slong &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20slong2_20_3e_35',['Var&lt; slong2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20slong3_20_3e_36',['Var&lt; slong3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20slong4_20_3e_37',['Var&lt; slong4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20soaview_3c_20t_20_3e_20_3e_38',['Var&lt; SOAView&lt; T &gt; &gt;',['../structluisa_1_1compute_1_1_var_3_01_s_o_a_view_3_01_t_01_4_01_4.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_39',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20bool_2c_20n_20_3e_40',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; bool, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20bool2_2c_20n_20_3e_41',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; bool2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20bool3_2c_20n_20_3e_42',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; bool3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20bool4_2c_20n_20_3e_43',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; bool4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float_2c_20n_20_3e_44',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float2_2c_20n_20_3e_45',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float2x2_2c_20n_20_3e_46',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float2x2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float3_2c_20n_20_3e_47',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float3x3_2c_20n_20_3e_48',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float3x3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float4_2c_20n_20_3e_49',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20float4x4_2c_20n_20_3e_50',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; float4x4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20half_2c_20n_20_3e_51',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; half, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20half2_2c_20n_20_3e_52',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; half2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20half3_2c_20n_20_3e_53',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; half3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20half4_2c_20n_20_3e_54',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; half4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20int_2c_20n_20_3e_55',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; int, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20int2_2c_20n_20_3e_56',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; int2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20int3_2c_20n_20_3e_57',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; int3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20int4_2c_20n_20_3e_58',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; int4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20short_2c_20n_20_3e_59',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; short, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20short2_2c_20n_20_3e_60',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; short2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20short3_2c_20n_20_3e_61',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; short3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20short4_2c_20n_20_3e_62',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; short4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20slong_2c_20n_20_3e_63',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; slong, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20slong2_2c_20n_20_3e_64',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; slong2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20slong3_2c_20n_20_3e_65',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; slong3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20slong4_2c_20n_20_3e_66',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; slong4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20uint_2c_20n_20_3e_67',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; uint, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20uint2_2c_20n_20_3e_68',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; uint2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20uint3_2c_20n_20_3e_69',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; uint3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20uint4_2c_20n_20_3e_70',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; uint4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ulong_2c_20n_20_3e_71',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ulong, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ulong2_2c_20n_20_3e_72',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ulong2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ulong3_2c_20n_20_3e_73',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ulong3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ulong4_2c_20n_20_3e_74',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ulong4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ushort_2c_20n_20_3e_75',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ushort, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ushort2_2c_20n_20_3e_76',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ushort2, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ushort3_2c_20n_20_3e_77',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ushort3, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20std_3a_3aarray_3c_20expr_5fvalue_5ft_3c_20t_20_3e_2c_20n_20_3e_20_3e_3c_20ushort4_2c_20n_20_3e_78',['Var&lt; std::array&lt; expr_value_t&lt; T &gt;, N &gt; &gt;&lt; ushort4, N &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20t_20_3e_20_26_79',['Var&lt; T &gt; &amp;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20uint_20_3e_80',['Var&lt; uint &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20uint2_20_3e_81',['Var&lt; uint2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20uint3_20_3e_82',['Var&lt; uint3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20uint4_20_3e_83',['Var&lt; uint4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ulong_20_3e_84',['Var&lt; ulong &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ulong2_20_3e_85',['Var&lt; ulong2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ulong3_20_3e_86',['Var&lt; ulong3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ulong4_20_3e_87',['Var&lt; ulong4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ushort_20_3e_88',['Var&lt; ushort &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ushort2_20_3e_89',['Var&lt; ushort2 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ushort3_20_3e_90',['Var&lt; ushort3 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20ushort4_20_3e_91',['Var&lt; ushort4 &gt;',['../structluisa_1_1compute_1_1_var.html',1,'luisa::compute']]],
  ['var_3c_20volumeview_3c_20t_20_3e_20_3e_92',['Var&lt; VolumeView&lt; T &gt; &gt;',['../structluisa_1_1compute_1_1_var_3_01_volume_view_3_01_t_01_4_01_4.html',1,'luisa::compute']]],
  ['variable_93',['Variable',['../classluisa_1_1compute_1_1_variable.html',1,'luisa::compute']]],
  ['variant_94',['variant',['../classeastl_1_1variant.html',1,'eastl::variant&lt; Types &gt;'],['../classluisa_1_1variant.html',1,'luisa::variant&lt; Types &gt;']]],
  ['variant_5falternative_95',['variant_alternative',['../structeastl_1_1variant__alternative.html',1,'eastl']]],
  ['variant_5falternative_3c_20i_2c_20const_20t_20_3e_96',['variant_alternative&lt; I, const T &gt;',['../structeastl_1_1variant__alternative_3_01_i_00_01const_01_t_01_4.html',1,'eastl']]],
  ['variant_5falternative_3c_20i_2c_20const_20volatile_20t_20_3e_97',['variant_alternative&lt; I, const volatile T &gt;',['../structeastl_1_1variant__alternative_3_01_i_00_01const_01volatile_01_t_01_4.html',1,'eastl']]],
  ['variant_5falternative_3c_20i_2c_20variant_3c_20types_2e_2e_2e_20_3e_20_3e_98',['variant_alternative&lt; I, variant&lt; Types... &gt; &gt;',['../structeastl_1_1variant__alternative_3_01_i_00_01variant_3_01_types_8_8_8_01_4_01_4.html',1,'eastl']]],
  ['variant_5falternative_3c_20i_2c_20volatile_20t_20_3e_99',['variant_alternative&lt; I, volatile T &gt;',['../structeastl_1_1variant__alternative_3_01_i_00_01volatile_01_t_01_4.html',1,'eastl']]],
  ['variant_5falternative_5fhelper_100',['variant_alternative_helper',['../structeastl_1_1variant__alternative__helper.html',1,'eastl']]],
  ['variant_5falternative_5fhelper_3c_200_2c_20head_2c_20tail_2e_2e_2e_20_3e_101',['variant_alternative_helper&lt; 0, Head, Tail... &gt;',['../structeastl_1_1variant__alternative__helper_3_010_00_01_head_00_01_tail_8_8_8_01_4.html',1,'eastl']]],
  ['variant_5falternative_5fhelper_3c_20i_2c_20head_2c_20tail_2e_2e_2e_20_3e_102',['variant_alternative_helper&lt; I, Head, Tail... &gt;',['../structeastl_1_1variant__alternative__helper_3_01_i_00_01_head_00_01_tail_8_8_8_01_4.html',1,'eastl']]],
  ['variant_5falternative_5fhelper_3c_20i_2c_20types_2e_2e_2e_20_3e_103',['variant_alternative_helper&lt; I, Types... &gt;',['../structeastl_1_1variant__alternative__helper.html',1,'eastl']]],
  ['variant_5frelational_5fcomparison_104',['variant_relational_comparison',['../structeastl_1_1internal_1_1variant__relational__comparison.html',1,'eastl::internal']]],
  ['variant_5fsize_105',['variant_size',['../structeastl_1_1variant__size.html',1,'eastl']]],
  ['variant_5fsize_3c_20const_20t_20_3e_106',['variant_size&lt; const T &gt;',['../structeastl_1_1variant__size_3_01const_01_t_01_4.html',1,'eastl']]],
  ['variant_5fsize_3c_20const_20volatile_20t_20_3e_107',['variant_size&lt; const volatile T &gt;',['../structeastl_1_1variant__size_3_01const_01volatile_01_t_01_4.html',1,'eastl']]],
  ['variant_5fsize_3c_20luisa_3a_3acompute_3a_3adetail_3a_3aliteralvalue_20_3e_108',['variant_size&lt; luisa::compute::detail::LiteralValue &gt;',['../structeastl_1_1variant__size_3_01luisa_1_1compute_1_1detail_1_1_literal_value_01_4.html',1,'eastl']]],
  ['variant_5fsize_3c_20luisa_3a_3acompute_3a_3adetail_3a_3aliteralvaluevariant_20_3e_109',['variant_size&lt; luisa::compute::detail::LiteralValueVariant &gt;',['../structeastl_1_1variant__size.html',1,'eastl']]],
  ['variant_5fsize_3c_20variant_3c_20types_2e_2e_2e_20_3e_20_3e_110',['variant_size&lt; variant&lt; Types... &gt; &gt;',['../structeastl_1_1variant__size_3_01variant_3_01_types_8_8_8_01_4_01_4.html',1,'eastl']]],
  ['variant_5fsize_3c_20volatile_20t_20_3e_111',['variant_size&lt; volatile T &gt;',['../structeastl_1_1variant__size_3_01volatile_01_t_01_4.html',1,'eastl']]],
  ['variant_5fstorage_112',['variant_storage',['../structeastl_1_1variant__storage.html',1,'eastl']]],
  ['variant_5fstorage_3c_20conjunction_5fv_3c_20is_5ftrivially_5fdestructible_3c_20types_20_3e_2e_2e_2e_20_3e_2c_20types_2e_2e_2e_20_3e_113',['variant_storage&lt; conjunction_v&lt; is_trivially_destructible&lt; Types &gt;... &gt;, Types... &gt;',['../structeastl_1_1variant__storage.html',1,'eastl']]],
  ['variant_5fstorage_3c_20false_2c_20types_2e_2e_2e_20_3e_114',['variant_storage&lt; false, Types... &gt;',['../structeastl_1_1variant__storage_3_01false_00_01_types_8_8_8_01_4.html',1,'eastl']]],
  ['variant_5fstorage_3c_20true_2c_20types_2e_2e_2e_20_3e_115',['variant_storage&lt; true, Types... &gt;',['../structeastl_1_1variant__storage_3_01true_00_01_types_8_8_8_01_4.html',1,'eastl']]],
  ['vec3_116',['Vec3',['../struct_vec3.html',1,'']]],
  ['vector_117',['Vector',['../structluisa_1_1_vector.html',1,'luisa']]],
  ['vector_118',['vector',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector2_119',['vector2',['../classsource__runtime_1_1math_1_1vector2.html',1,'source_runtime::math']]],
  ['vector2_3c_20float_20_3e_120',['vector2&lt; float &gt;',['../classsource__runtime_1_1math_1_1vector2.html',1,'source_runtime::math']]],
  ['vector2_3c_20int32_5ft_20_3e_121',['vector2&lt; int32_t &gt;',['../classsource__runtime_1_1math_1_1vector2.html',1,'source_runtime::math']]],
  ['vector3_122',['vector3',['../classsource__runtime_1_1math_1_1vector3.html',1,'source_runtime::math']]],
  ['vector3_3c_20float_20_3e_123',['vector3&lt; float &gt;',['../classsource__runtime_1_1math_1_1vector3.html',1,'source_runtime::math']]],
  ['vector3_3c_20int32_5ft_20_3e_124',['vector3&lt; int32_t &gt;',['../classsource__runtime_1_1math_1_1vector3.html',1,'source_runtime::math']]],
  ['vector_3c_20bitvectorwordtype_2c_20eastlallocatortype_20_3e_125',['vector&lt; BitvectorWordType, EASTLAllocatorType &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_3c_20const_20luisa_3a_3acompute_3a_3astatement_20_2a_20_3e_126',['vector&lt; const luisa::compute::Statement * &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_3c_20eastl_3a_3apair_3c_20key_2c_20t_20_3e_2c_20eastlallocatortype_20_3e_127',['vector&lt; eastl::pair&lt; Key, T &gt;, EASTLAllocatorType &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_3c_20float_2c_20n_20_3e_128',['Vector&lt; float, N &gt;',['../structluisa_1_1_vector.html',1,'luisa']]],
  ['vector_3c_20key_2c_20eastlallocatortype_20_3e_129',['vector&lt; Key, EASTLAllocatorType &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_3c_20t_2c_20allocator_20_3e_130',['vector&lt; T, Allocator &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_3c_20t_2c_20fixed_5fallocator_5ftype_20_3e_131',['vector&lt; T, fixed_allocator_type &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_3c_20t_2c_20fixed_5fvector_5fallocator_3c_20sizeof_28t_29_2c_20nodecount_2c_20eastl_5falign_5fof_28t_29_2c_200_2c_20benableoverflow_2c_20eastlallocatortype_20_3e_20_3e_132',['vector&lt; T, fixed_vector_allocator&lt; sizeof(T), nodeCount, EASTL_ALIGN_OF(T), 0, bEnableOverflow, EASTLAllocatorType &gt; &gt;',['../classeastl_1_1vector.html',1,'eastl']]],
  ['vector_5falignment_133',['vector_alignment',['../structluisa_1_1detail_1_1vector__alignment.html',1,'luisa::detail']]],
  ['vector_5fbody_134',['Vector_Body',['../structluisa_1_1compute_1_1ir_1_1_type_1_1_vector___body.html',1,'luisa::compute::ir::Type::Vector_Body'],['../structluisa_1_1compute_1_1ir_1_1_vector_element_type_1_1_vector___body.html',1,'luisa::compute::ir::VectorElementType::Vector_Body']]],
  ['vector_5fdimension_5fimpl_135',['vector_dimension_impl',['../structluisa_1_1detail_1_1vector__dimension__impl.html',1,'luisa::detail']]],
  ['vector_5fdimension_5fimpl_3c_20std_3a_3aremove_5fcvref_5ft_3c_20t_20_3e_20_3e_136',['vector_dimension_impl&lt; std::remove_cvref_t&lt; T &gt; &gt;',['../structluisa_1_1detail_1_1vector__dimension__impl.html',1,'luisa::detail']]],
  ['vector_5fdimension_5fimpl_3c_20std_3a_3aremove_5fcvref_5ft_3c_20t_20_3e_20_3e_3c_20expr_5fvalue_5ft_3c_20t_20_3e_20_3e_137',['vector_dimension_impl&lt; std::remove_cvref_t&lt; T &gt; &gt;&lt; expr_value_t&lt; T &gt; &gt;',['../structluisa_1_1detail_1_1vector__dimension__impl.html',1,'luisa::detail']]],
  ['vector_5fdimension_5fimpl_3c_20vector_3c_20t_2c_20n_20_3e_20_3e_138',['vector_dimension_impl&lt; Vector&lt; T, N &gt; &gt;',['../structluisa_1_1detail_1_1vector__dimension__impl_3_01_vector_3_01_t_00_01_n_01_4_01_4.html',1,'luisa::detail']]],
  ['vector_5felement_5fimpl_139',['vector_element_impl',['../structluisa_1_1detail_1_1vector__element__impl.html',1,'luisa::detail']]],
  ['vector_5felement_5fimpl_3c_20std_3a_3aremove_5fcvref_5ft_3c_20t_20_3e_20_3e_140',['vector_element_impl&lt; std::remove_cvref_t&lt; T &gt; &gt;',['../structluisa_1_1detail_1_1vector__element__impl.html',1,'luisa::detail']]],
  ['vector_5felement_5fimpl_3c_20std_3a_3aremove_5fcvref_5ft_3c_20t_20_3e_20_3e_3c_20expr_5fvalue_5ft_3c_20t_20_3e_20_3e_141',['vector_element_impl&lt; std::remove_cvref_t&lt; T &gt; &gt;&lt; expr_value_t&lt; T &gt; &gt;',['../structluisa_1_1detail_1_1vector__element__impl.html',1,'luisa::detail']]],
  ['vector_5felement_5fimpl_3c_20vector_3c_20t_2c_20n_20_3e_20_3e_142',['vector_element_impl&lt; Vector&lt; T, N &gt; &gt;',['../structluisa_1_1detail_1_1vector__element__impl_3_01_vector_3_01_t_00_01_n_01_4_01_4.html',1,'luisa::detail']]],
  ['vector_5fmap_143',['vector_map',['../classeastl_1_1vector__map.html',1,'eastl']]],
  ['vector_5fmap_3c_20key_2c_20t_2c_20compare_2c_20allocator_2c_20randomaccesscontainer_20_3e_144',['vector_map&lt; Key, T, Compare, Allocator, RandomAccessContainer &gt;',['../classeastl_1_1vector__map.html',1,'eastl']]],
  ['vector_5fmap_3c_20key_2c_20value_2c_20compare_20_3e_145',['vector_map&lt; Key, Value, Compare &gt;',['../classeastl_1_1vector__map.html',1,'eastl']]],
  ['vector_5fmultimap_146',['vector_multimap',['../classeastl_1_1vector__multimap.html',1,'eastl']]],
  ['vector_5fmultimap_3c_20key_2c_20t_2c_20compare_2c_20allocator_2c_20randomaccesscontainer_20_3e_147',['vector_multimap&lt; Key, T, Compare, Allocator, RandomAccessContainer &gt;',['../classeastl_1_1vector__multimap.html',1,'eastl']]],
  ['vector_5fmultimap_3c_20key_2c_20value_2c_20compare_20_3e_148',['vector_multimap&lt; Key, Value, Compare &gt;',['../classeastl_1_1vector__multimap.html',1,'eastl']]],
  ['vector_5fmultiset_149',['vector_multiset',['../classeastl_1_1vector__multiset.html',1,'eastl']]],
  ['vector_5fmultiset_3c_20key_2c_20compare_20_3e_150',['vector_multiset&lt; Key, Compare &gt;',['../classeastl_1_1vector__multiset.html',1,'eastl']]],
  ['vector_5fmultiset_3c_20key_2c_20compare_2c_20allocator_2c_20randomaccesscontainer_20_3e_151',['vector_multiset&lt; Key, Compare, Allocator, RandomAccessContainer &gt;',['../classeastl_1_1vector__multiset.html',1,'eastl']]],
  ['vector_5fset_152',['vector_set',['../classeastl_1_1vector__set.html',1,'eastl']]],
  ['vector_5fset_3c_20key_2c_20compare_20_3e_153',['vector_set&lt; Key, Compare &gt;',['../classeastl_1_1vector__set.html',1,'eastl']]],
  ['vector_5fset_3c_20key_2c_20compare_2c_20allocator_2c_20randomaccesscontainer_20_3e_154',['vector_set&lt; Key, Compare, Allocator, RandomAccessContainer &gt;',['../classeastl_1_1vector__set.html',1,'eastl']]],
  ['vectorbase_155',['VectorBase',['../structeastl_1_1_vector_base.html',1,'eastl']]],
  ['vectorbase_3c_20bitvectorwordtype_2c_20eastlallocatortype_20_3e_156',['VectorBase&lt; BitvectorWordType, EASTLAllocatorType &gt;',['../structeastl_1_1_vector_base.html',1,'eastl']]],
  ['vectorbase_3c_20const_20luisa_3a_3acompute_3a_3astatement_20_2a_2c_20eastlallocatortype_20_3e_157',['VectorBase&lt; const luisa::compute::Statement *, EASTLAllocatorType &gt;',['../structeastl_1_1_vector_base.html',1,'eastl']]],
  ['vectorbase_3c_20key_2c_20eastlallocatortype_20_3e_158',['VectorBase&lt; Key, EASTLAllocatorType &gt;',['../structeastl_1_1_vector_base.html',1,'eastl']]],
  ['vectorbase_3c_20t_2c_20eastlallocatortype_20_3e_159',['VectorBase&lt; T, EASTLAllocatorType &gt;',['../structeastl_1_1_vector_base.html',1,'eastl']]],
  ['vectorbase_3c_20t_2c_20fixed_5fvector_5fallocator_3c_20sizeof_28t_29_2c_20nodecount_2c_20eastl_5falign_5fof_28t_29_2c_200_2c_20benableoverflow_2c_20eastlallocatortype_20_3e_20_3e_160',['VectorBase&lt; T, fixed_vector_allocator&lt; sizeof(T), nodeCount, EASTL_ALIGN_OF(T), 0, bEnableOverflow, EASTLAllocatorType &gt; &gt;',['../structeastl_1_1_vector_base.html',1,'eastl']]],
  ['vectorelementtype_161',['VectorElementType',['../structluisa_1_1compute_1_1ir_1_1_vector_element_type.html',1,'luisa::compute::ir']]],
  ['vectorized_162',['vectorized',['../structluisa_1_1compute_1_1detail_1_1vectorized.html',1,'luisa::compute::detail']]],
  ['vectorized_3c_20t_2c_201u_20_3e_163',['vectorized&lt; T, 1u &gt;',['../structluisa_1_1compute_1_1detail_1_1vectorized_3_01_t_00_011u_01_4.html',1,'luisa::compute::detail']]],
  ['vectorized_5fdimension_164',['vectorized_dimension',['../structluisa_1_1compute_1_1detail_1_1vectorized__dimension.html',1,'luisa::compute::detail']]],
  ['vectorized_5fdimension_3c_20first_2c_20other_2e_2e_2e_20_3e_165',['vectorized_dimension&lt; First, Other... &gt;',['../structluisa_1_1compute_1_1detail_1_1vectorized__dimension_3_01_first_00_01_other_8_8_8_01_4.html',1,'luisa::compute::detail']]],
  ['vectorized_5fdimension_3c_20t_20_3e_166',['vectorized_dimension&lt; T &gt;',['../structluisa_1_1compute_1_1detail_1_1vectorized__dimension_3_01_t_01_4.html',1,'luisa::compute::detail']]],
  ['vectorstorage_167',['VectorStorage',['../structluisa_1_1detail_1_1_vector_storage.html',1,'luisa::detail']]],
  ['vectorstorage_3c_20t_2c_202_20_3e_168',['VectorStorage&lt; T, 2 &gt;',['../structluisa_1_1detail_1_1_vector_storage_3_01_t_00_012_01_4.html',1,'luisa::detail']]],
  ['vectorstorage_3c_20t_2c_203_20_3e_169',['VectorStorage&lt; T, 3 &gt;',['../structluisa_1_1detail_1_1_vector_storage_3_01_t_00_013_01_4.html',1,'luisa::detail']]],
  ['vectorstorage_3c_20t_2c_204_20_3e_170',['VectorStorage&lt; T, 4 &gt;',['../structluisa_1_1detail_1_1_vector_storage_3_01_t_00_014_01_4.html',1,'luisa::detail']]],
  ['vectorstorage_3c_20value_5ftype_2c_20n_20_3e_171',['VectorStorage&lt; value_type, N &gt;',['../structluisa_1_1detail_1_1_vector_storage.html',1,'luisa::detail']]],
  ['vectortype_172',['VectorType',['../structluisa_1_1compute_1_1ir_1_1_vector_type.html',1,'luisa::compute::ir']]],
  ['vertex_173',['Vertex',['../struct_vertex.html',1,'']]],
  ['vertex_5fconstant_5fbuffer_5fdx10_174',['VERTEX_CONSTANT_BUFFER_DX10',['../struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r___d_x10.html',1,'']]],
  ['vertex_5fconstant_5fbuffer_5fdx11_175',['VERTEX_CONSTANT_BUFFER_DX11',['../struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r___d_x11.html',1,'']]],
  ['vertex_5fconstant_5fbuffer_5fdx12_176',['VERTEX_CONSTANT_BUFFER_DX12',['../struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r___d_x12.html',1,'']]],
  ['vertex_5ft_177',['vertex_t',['../structvertex__t.html',1,'']]],
  ['vertexattribute_178',['VertexAttribute',['../structluisa_1_1compute_1_1_vertex_attribute.html',1,'luisa::compute']]],
  ['vertexbufferview_179',['VertexBufferView',['../classluisa_1_1compute_1_1_vertex_buffer_view.html',1,'luisa::compute']]],
  ['vformat_5fargs_180',['vformat_args',['../structdetail_1_1vformat__args.html',1,'detail']]],
  ['vformat_5fargs_3c_20char_20_3e_181',['vformat_args&lt; char &gt;',['../structdetail_1_1vformat__args_3_01char_01_4.html',1,'detail']]],
  ['view_182',['view',['../structdetail_1_1view.html',1,'detail']]],
  ['viewport_183',['Viewport',['../structluisa_1_1compute_1_1_viewport.html',1,'luisa::compute']]],
  ['visitor_5fcaller_5fn_184',['visitor_caller_n',['../structeastl_1_1visitor__caller__n.html',1,'eastl']]],
  ['visitor_5fcaller_5fn_3c_20index_5fsequence_3c_20variantindices_2e_2e_2e_20_3e_2c_20visitor_2c_20variants_2e_2e_2e_20_3e_185',['visitor_caller_n&lt; index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;',['../structeastl_1_1visitor__caller__n_3_01index__sequence_3_01_variant_indices_8_8_8_01_4_00_01_visitor_00_01_variants_8_8_8_01_4.html',1,'eastl']]],
  ['visitor_5fcaller_5fn_5fr_186',['visitor_caller_n_r',['../structeastl_1_1visitor__caller__n__r.html',1,'eastl']]],
  ['visitor_5fcaller_5fn_5fr_3c_20r_2c_20index_5fsequence_3c_20variantindices_2e_2e_2e_20_3e_2c_20visitor_2c_20variants_2e_2e_2e_20_3e_187',['visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_41a164e600e86281933738b778f5e7065.html',1,'eastl']]],
  ['visitor_5fcaller_5fone_188',['visitor_caller_one',['../structeastl_1_1visitor__caller__one.html',1,'eastl']]],
  ['visitor_5fcaller_5fone_5fr_189',['visitor_caller_one_r',['../structeastl_1_1visitor__caller__one__r.html',1,'eastl']]],
  ['visitor_5fleaf_5fr_190',['visitor_leaf_r',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_4b3ee2f633d393a08ca6c6a5a406ec5ea.html',1,'eastl::visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;']]],
  ['visitor_5fleaf_5fr_3c_20const_20void_2c_20variantargindices_2e_2e_2e_20_3e_191',['visitor_leaf_r&lt; const void, VariantArgIndices... &gt;',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_439056516c95d6d9dd3d0ae4f7bfc3a25.html',1,'eastl::visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;']]],
  ['visitor_5fleaf_5fr_3c_20const_20volatile_20void_2c_20variantargindices_2e_2e_2e_20_3e_192',['visitor_leaf_r&lt; const volatile void, VariantArgIndices... &gt;',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_4ddc3b6c2261c5dde7e3e270f045858dd.html',1,'eastl::visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;']]],
  ['visitor_5fleaf_5fr_3c_20void_2c_20variantargindices_2e_2e_2e_20_3e_193',['visitor_leaf_r&lt; void, VariantArgIndices... &gt;',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_48a1c6c251f9146309afe0c8122b50310.html',1,'eastl::visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;']]],
  ['visitor_5fleaf_5fr_3c_20volatile_20void_2c_20variantargindices_2e_2e_2e_20_3e_194',['visitor_leaf_r&lt; volatile void, VariantArgIndices... &gt;',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_4991999fc689fdb38e065fae79fcdba0b.html',1,'eastl::visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;']]],
  ['visitor_5fr_195',['visitor_r',['../structeastl_1_1visitor__r.html',1,'eastl']]],
  ['visitor_5fr_3c_20const_20void_20_3e_196',['visitor_r&lt; const void &gt;',['../structeastl_1_1visitor__r_3_01const_01void_01_4.html',1,'eastl']]],
  ['visitor_5fr_3c_20const_20volatile_20void_20_3e_197',['visitor_r&lt; const volatile void &gt;',['../structeastl_1_1visitor__r_3_01const_01volatile_01void_01_4.html',1,'eastl']]],
  ['visitor_5fr_3c_20void_20_3e_198',['visitor_r&lt; void &gt;',['../structeastl_1_1visitor__r_3_01void_01_4.html',1,'eastl']]],
  ['visitor_5fr_3c_20volatile_20void_20_3e_199',['visitor_r&lt; volatile void &gt;',['../structeastl_1_1visitor__r_3_01volatile_01void_01_4.html',1,'eastl']]],
  ['visitor_5frecurse_5fr_200',['visitor_recurse_r',['../structeastl_1_1visitor__caller__n__r_3_01_r_00_01index__sequence_3_01_variant_indices_8_8_8_01_474f1d32773c3a60144e5867667b76fa5.html',1,'eastl::visitor_caller_n_r&lt; R, index_sequence&lt; VariantIndices... &gt;, Visitor, Variants... &gt;']]],
  ['vkacquirenextimageinfokhr_201',['VkAcquireNextImageInfoKHR',['../struct_vk_acquire_next_image_info_k_h_r.html',1,'']]],
  ['vkallocationcallbacks_202',['VkAllocationCallbacks',['../struct_vk_allocation_callbacks.html',1,'']]],
  ['vkapplicationinfo_203',['VkApplicationInfo',['../struct_vk_application_info.html',1,'']]],
  ['vkattachmentdescription_204',['VkAttachmentDescription',['../struct_vk_attachment_description.html',1,'']]],
  ['vkattachmentdescription2_205',['VkAttachmentDescription2',['../struct_vk_attachment_description2.html',1,'']]],
  ['vkattachmentdescriptionstencillayout_206',['VkAttachmentDescriptionStencilLayout',['../struct_vk_attachment_description_stencil_layout.html',1,'']]],
  ['vkattachmentreference_207',['VkAttachmentReference',['../struct_vk_attachment_reference.html',1,'']]],
  ['vkattachmentreference2_208',['VkAttachmentReference2',['../struct_vk_attachment_reference2.html',1,'']]],
  ['vkattachmentreferencestencillayout_209',['VkAttachmentReferenceStencilLayout',['../struct_vk_attachment_reference_stencil_layout.html',1,'']]],
  ['vkbaseinstructure_210',['VkBaseInStructure',['../struct_vk_base_in_structure.html',1,'']]],
  ['vkbaseoutstructure_211',['VkBaseOutStructure',['../struct_vk_base_out_structure.html',1,'']]],
  ['vkbindbuffermemorydevicegroupinfo_212',['VkBindBufferMemoryDeviceGroupInfo',['../struct_vk_bind_buffer_memory_device_group_info.html',1,'']]],
  ['vkbindbuffermemoryinfo_213',['VkBindBufferMemoryInfo',['../struct_vk_bind_buffer_memory_info.html',1,'']]],
  ['vkbindimagememorydevicegroupinfo_214',['VkBindImageMemoryDeviceGroupInfo',['../struct_vk_bind_image_memory_device_group_info.html',1,'']]],
  ['vkbindimagememoryinfo_215',['VkBindImageMemoryInfo',['../struct_vk_bind_image_memory_info.html',1,'']]],
  ['vkbindimagememoryswapchaininfokhr_216',['VkBindImageMemorySwapchainInfoKHR',['../struct_vk_bind_image_memory_swapchain_info_k_h_r.html',1,'']]],
  ['vkbindimageplanememoryinfo_217',['VkBindImagePlaneMemoryInfo',['../struct_vk_bind_image_plane_memory_info.html',1,'']]],
  ['vkbindsparseinfo_218',['VkBindSparseInfo',['../struct_vk_bind_sparse_info.html',1,'']]],
  ['vkblitimageinfo2_219',['VkBlitImageInfo2',['../struct_vk_blit_image_info2.html',1,'']]],
  ['vkbuffercopy_220',['VkBufferCopy',['../struct_vk_buffer_copy.html',1,'']]],
  ['vkbuffercopy2_221',['VkBufferCopy2',['../struct_vk_buffer_copy2.html',1,'']]],
  ['vkbuffercreateinfo_222',['VkBufferCreateInfo',['../struct_vk_buffer_create_info.html',1,'']]],
  ['vkbufferdeviceaddressinfo_223',['VkBufferDeviceAddressInfo',['../struct_vk_buffer_device_address_info.html',1,'']]],
  ['vkbufferimagecopy_224',['VkBufferImageCopy',['../struct_vk_buffer_image_copy.html',1,'']]],
  ['vkbufferimagecopy2_225',['VkBufferImageCopy2',['../struct_vk_buffer_image_copy2.html',1,'']]],
  ['vkbuffermemorybarrier_226',['VkBufferMemoryBarrier',['../struct_vk_buffer_memory_barrier.html',1,'']]],
  ['vkbuffermemorybarrier2_227',['VkBufferMemoryBarrier2',['../struct_vk_buffer_memory_barrier2.html',1,'']]],
  ['vkbuffermemoryrequirementsinfo2_228',['VkBufferMemoryRequirementsInfo2',['../struct_vk_buffer_memory_requirements_info2.html',1,'']]],
  ['vkbufferopaquecaptureaddresscreateinfo_229',['VkBufferOpaqueCaptureAddressCreateInfo',['../struct_vk_buffer_opaque_capture_address_create_info.html',1,'']]],
  ['vkbufferviewcreateinfo_230',['VkBufferViewCreateInfo',['../struct_vk_buffer_view_create_info.html',1,'']]],
  ['vkclearattachment_231',['VkClearAttachment',['../struct_vk_clear_attachment.html',1,'']]],
  ['vkclearcolorvalue_232',['VkClearColorValue',['../union_vk_clear_color_value.html',1,'']]],
  ['vkcleardepthstencilvalue_233',['VkClearDepthStencilValue',['../struct_vk_clear_depth_stencil_value.html',1,'']]],
  ['vkclearrect_234',['VkClearRect',['../struct_vk_clear_rect.html',1,'']]],
  ['vkclearvalue_235',['VkClearValue',['../union_vk_clear_value.html',1,'']]],
  ['vkcommandbufferallocateinfo_236',['VkCommandBufferAllocateInfo',['../struct_vk_command_buffer_allocate_info.html',1,'']]],
  ['vkcommandbufferbegininfo_237',['VkCommandBufferBeginInfo',['../struct_vk_command_buffer_begin_info.html',1,'']]],
  ['vkcommandbufferinheritanceinfo_238',['VkCommandBufferInheritanceInfo',['../struct_vk_command_buffer_inheritance_info.html',1,'']]],
  ['vkcommandbufferinheritancerenderinginfo_239',['VkCommandBufferInheritanceRenderingInfo',['../struct_vk_command_buffer_inheritance_rendering_info.html',1,'']]],
  ['vkcommandbuffersubmitinfo_240',['VkCommandBufferSubmitInfo',['../struct_vk_command_buffer_submit_info.html',1,'']]],
  ['vkcommandpoolcreateinfo_241',['VkCommandPoolCreateInfo',['../struct_vk_command_pool_create_info.html',1,'']]],
  ['vkcomponentmapping_242',['VkComponentMapping',['../struct_vk_component_mapping.html',1,'']]],
  ['vkcomputepipelinecreateinfo_243',['VkComputePipelineCreateInfo',['../struct_vk_compute_pipeline_create_info.html',1,'']]],
  ['vkconformanceversion_244',['VkConformanceVersion',['../struct_vk_conformance_version.html',1,'']]],
  ['vkcopybufferinfo2_245',['VkCopyBufferInfo2',['../struct_vk_copy_buffer_info2.html',1,'']]],
  ['vkcopybuffertoimageinfo2_246',['VkCopyBufferToImageInfo2',['../struct_vk_copy_buffer_to_image_info2.html',1,'']]],
  ['vkcopydescriptorset_247',['VkCopyDescriptorSet',['../struct_vk_copy_descriptor_set.html',1,'']]],
  ['vkcopyimageinfo2_248',['VkCopyImageInfo2',['../struct_vk_copy_image_info2.html',1,'']]],
  ['vkcopyimagetobufferinfo2_249',['VkCopyImageToBufferInfo2',['../struct_vk_copy_image_to_buffer_info2.html',1,'']]],
  ['vkdebugreportcallbackcreateinfoext_250',['VkDebugReportCallbackCreateInfoEXT',['../struct_vk_debug_report_callback_create_info_e_x_t.html',1,'']]],
  ['vkdependencyinfo_251',['VkDependencyInfo',['../struct_vk_dependency_info.html',1,'']]],
  ['vkdescriptorbufferinfo_252',['VkDescriptorBufferInfo',['../struct_vk_descriptor_buffer_info.html',1,'']]],
  ['vkdescriptorimageinfo_253',['VkDescriptorImageInfo',['../struct_vk_descriptor_image_info.html',1,'']]],
  ['vkdescriptorpoolcreateinfo_254',['VkDescriptorPoolCreateInfo',['../struct_vk_descriptor_pool_create_info.html',1,'']]],
  ['vkdescriptorpoolinlineuniformblockcreateinfo_255',['VkDescriptorPoolInlineUniformBlockCreateInfo',['../struct_vk_descriptor_pool_inline_uniform_block_create_info.html',1,'']]],
  ['vkdescriptorpoolsize_256',['VkDescriptorPoolSize',['../struct_vk_descriptor_pool_size.html',1,'']]],
  ['vkdescriptorsetallocateinfo_257',['VkDescriptorSetAllocateInfo',['../struct_vk_descriptor_set_allocate_info.html',1,'']]],
  ['vkdescriptorsetlayoutbinding_258',['VkDescriptorSetLayoutBinding',['../struct_vk_descriptor_set_layout_binding.html',1,'']]],
  ['vkdescriptorsetlayoutbindingflagscreateinfo_259',['VkDescriptorSetLayoutBindingFlagsCreateInfo',['../struct_vk_descriptor_set_layout_binding_flags_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutcreateinfo_260',['VkDescriptorSetLayoutCreateInfo',['../struct_vk_descriptor_set_layout_create_info.html',1,'']]],
  ['vkdescriptorsetlayoutsupport_261',['VkDescriptorSetLayoutSupport',['../struct_vk_descriptor_set_layout_support.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountallocateinfo_262',['VkDescriptorSetVariableDescriptorCountAllocateInfo',['../struct_vk_descriptor_set_variable_descriptor_count_allocate_info.html',1,'']]],
  ['vkdescriptorsetvariabledescriptorcountlayoutsupport_263',['VkDescriptorSetVariableDescriptorCountLayoutSupport',['../struct_vk_descriptor_set_variable_descriptor_count_layout_support.html',1,'']]],
  ['vkdescriptorupdatetemplatecreateinfo_264',['VkDescriptorUpdateTemplateCreateInfo',['../struct_vk_descriptor_update_template_create_info.html',1,'']]],
  ['vkdescriptorupdatetemplateentry_265',['VkDescriptorUpdateTemplateEntry',['../struct_vk_descriptor_update_template_entry.html',1,'']]],
  ['vkdevicebuffermemoryrequirements_266',['VkDeviceBufferMemoryRequirements',['../struct_vk_device_buffer_memory_requirements.html',1,'']]],
  ['vkdevicecreateinfo_267',['VkDeviceCreateInfo',['../struct_vk_device_create_info.html',1,'']]],
  ['vkdevicegroupbindsparseinfo_268',['VkDeviceGroupBindSparseInfo',['../struct_vk_device_group_bind_sparse_info.html',1,'']]],
  ['vkdevicegroupcommandbufferbegininfo_269',['VkDeviceGroupCommandBufferBeginInfo',['../struct_vk_device_group_command_buffer_begin_info.html',1,'']]],
  ['vkdevicegroupdevicecreateinfo_270',['VkDeviceGroupDeviceCreateInfo',['../struct_vk_device_group_device_create_info.html',1,'']]],
  ['vkdevicegrouppresentcapabilitieskhr_271',['VkDeviceGroupPresentCapabilitiesKHR',['../struct_vk_device_group_present_capabilities_k_h_r.html',1,'']]],
  ['vkdevicegrouppresentinfokhr_272',['VkDeviceGroupPresentInfoKHR',['../struct_vk_device_group_present_info_k_h_r.html',1,'']]],
  ['vkdevicegrouprenderpassbegininfo_273',['VkDeviceGroupRenderPassBeginInfo',['../struct_vk_device_group_render_pass_begin_info.html',1,'']]],
  ['vkdevicegroupsubmitinfo_274',['VkDeviceGroupSubmitInfo',['../struct_vk_device_group_submit_info.html',1,'']]],
  ['vkdevicegroupswapchaincreateinfokhr_275',['VkDeviceGroupSwapchainCreateInfoKHR',['../struct_vk_device_group_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkdeviceimagememoryrequirements_276',['VkDeviceImageMemoryRequirements',['../struct_vk_device_image_memory_requirements.html',1,'']]],
  ['vkdevicememoryopaquecaptureaddressinfo_277',['VkDeviceMemoryOpaqueCaptureAddressInfo',['../struct_vk_device_memory_opaque_capture_address_info.html',1,'']]],
  ['vkdeviceprivatedatacreateinfo_278',['VkDevicePrivateDataCreateInfo',['../struct_vk_device_private_data_create_info.html',1,'']]],
  ['vkdevicequeuecreateinfo_279',['VkDeviceQueueCreateInfo',['../struct_vk_device_queue_create_info.html',1,'']]],
  ['vkdevicequeueinfo2_280',['VkDeviceQueueInfo2',['../struct_vk_device_queue_info2.html',1,'']]],
  ['vkdispatchindirectcommand_281',['VkDispatchIndirectCommand',['../struct_vk_dispatch_indirect_command.html',1,'']]],
  ['vkdrawindexedindirectcommand_282',['VkDrawIndexedIndirectCommand',['../struct_vk_draw_indexed_indirect_command.html',1,'']]],
  ['vkdrawindirectcommand_283',['VkDrawIndirectCommand',['../struct_vk_draw_indirect_command.html',1,'']]],
  ['vkeventcreateinfo_284',['VkEventCreateInfo',['../struct_vk_event_create_info.html',1,'']]],
  ['vkexportfencecreateinfo_285',['VkExportFenceCreateInfo',['../struct_vk_export_fence_create_info.html',1,'']]],
  ['vkexportmemoryallocateinfo_286',['VkExportMemoryAllocateInfo',['../struct_vk_export_memory_allocate_info.html',1,'']]],
  ['vkexportsemaphorecreateinfo_287',['VkExportSemaphoreCreateInfo',['../struct_vk_export_semaphore_create_info.html',1,'']]],
  ['vkextensionproperties_288',['VkExtensionProperties',['../struct_vk_extension_properties.html',1,'']]],
  ['vkextent2d_289',['VkExtent2D',['../struct_vk_extent2_d.html',1,'']]],
  ['vkextent3d_290',['VkExtent3D',['../struct_vk_extent3_d.html',1,'']]],
  ['vkexternalbufferproperties_291',['VkExternalBufferProperties',['../struct_vk_external_buffer_properties.html',1,'']]],
  ['vkexternalfenceproperties_292',['VkExternalFenceProperties',['../struct_vk_external_fence_properties.html',1,'']]],
  ['vkexternalimageformatproperties_293',['VkExternalImageFormatProperties',['../struct_vk_external_image_format_properties.html',1,'']]],
  ['vkexternalmemorybuffercreateinfo_294',['VkExternalMemoryBufferCreateInfo',['../struct_vk_external_memory_buffer_create_info.html',1,'']]],
  ['vkexternalmemoryimagecreateinfo_295',['VkExternalMemoryImageCreateInfo',['../struct_vk_external_memory_image_create_info.html',1,'']]],
  ['vkexternalmemoryproperties_296',['VkExternalMemoryProperties',['../struct_vk_external_memory_properties.html',1,'']]],
  ['vkexternalsemaphoreproperties_297',['VkExternalSemaphoreProperties',['../struct_vk_external_semaphore_properties.html',1,'']]],
  ['vkfencecreateinfo_298',['VkFenceCreateInfo',['../struct_vk_fence_create_info.html',1,'']]],
  ['vkformatproperties_299',['VkFormatProperties',['../struct_vk_format_properties.html',1,'']]],
  ['vkformatproperties2_300',['VkFormatProperties2',['../struct_vk_format_properties2.html',1,'']]],
  ['vkformatproperties3_301',['VkFormatProperties3',['../struct_vk_format_properties3.html',1,'']]],
  ['vkframebufferattachmentimageinfo_302',['VkFramebufferAttachmentImageInfo',['../struct_vk_framebuffer_attachment_image_info.html',1,'']]],
  ['vkframebufferattachmentscreateinfo_303',['VkFramebufferAttachmentsCreateInfo',['../struct_vk_framebuffer_attachments_create_info.html',1,'']]],
  ['vkframebuffercreateinfo_304',['VkFramebufferCreateInfo',['../struct_vk_framebuffer_create_info.html',1,'']]],
  ['vkgraphicspipelinecreateinfo_305',['VkGraphicsPipelineCreateInfo',['../struct_vk_graphics_pipeline_create_info.html',1,'']]],
  ['vkheadlesssurfacecreateinfoext_306',['VkHeadlessSurfaceCreateInfoEXT',['../struct_vk_headless_surface_create_info_e_x_t.html',1,'']]],
  ['vkimageblit_307',['VkImageBlit',['../struct_vk_image_blit.html',1,'']]],
  ['vkimageblit2_308',['VkImageBlit2',['../struct_vk_image_blit2.html',1,'']]],
  ['vkimagecopy_309',['VkImageCopy',['../struct_vk_image_copy.html',1,'']]],
  ['vkimagecopy2_310',['VkImageCopy2',['../struct_vk_image_copy2.html',1,'']]],
  ['vkimagecreateinfo_311',['VkImageCreateInfo',['../struct_vk_image_create_info.html',1,'']]],
  ['vkimageformatlistcreateinfo_312',['VkImageFormatListCreateInfo',['../struct_vk_image_format_list_create_info.html',1,'']]],
  ['vkimageformatproperties_313',['VkImageFormatProperties',['../struct_vk_image_format_properties.html',1,'']]],
  ['vkimageformatproperties2_314',['VkImageFormatProperties2',['../struct_vk_image_format_properties2.html',1,'']]],
  ['vkimagememorybarrier_315',['VkImageMemoryBarrier',['../struct_vk_image_memory_barrier.html',1,'']]],
  ['vkimagememorybarrier2_316',['VkImageMemoryBarrier2',['../struct_vk_image_memory_barrier2.html',1,'']]],
  ['vkimagememoryrequirementsinfo2_317',['VkImageMemoryRequirementsInfo2',['../struct_vk_image_memory_requirements_info2.html',1,'']]],
  ['vkimageplanememoryrequirementsinfo_318',['VkImagePlaneMemoryRequirementsInfo',['../struct_vk_image_plane_memory_requirements_info.html',1,'']]],
  ['vkimageresolve_319',['VkImageResolve',['../struct_vk_image_resolve.html',1,'']]],
  ['vkimageresolve2_320',['VkImageResolve2',['../struct_vk_image_resolve2.html',1,'']]],
  ['vkimagesparsememoryrequirementsinfo2_321',['VkImageSparseMemoryRequirementsInfo2',['../struct_vk_image_sparse_memory_requirements_info2.html',1,'']]],
  ['vkimagestencilusagecreateinfo_322',['VkImageStencilUsageCreateInfo',['../struct_vk_image_stencil_usage_create_info.html',1,'']]],
  ['vkimagesubresource_323',['VkImageSubresource',['../struct_vk_image_subresource.html',1,'']]],
  ['vkimagesubresourcelayers_324',['VkImageSubresourceLayers',['../struct_vk_image_subresource_layers.html',1,'']]],
  ['vkimagesubresourcerange_325',['VkImageSubresourceRange',['../struct_vk_image_subresource_range.html',1,'']]],
  ['vkimageswapchaincreateinfokhr_326',['VkImageSwapchainCreateInfoKHR',['../struct_vk_image_swapchain_create_info_k_h_r.html',1,'']]],
  ['vkimageviewcreateinfo_327',['VkImageViewCreateInfo',['../struct_vk_image_view_create_info.html',1,'']]],
  ['vkimageviewusagecreateinfo_328',['VkImageViewUsageCreateInfo',['../struct_vk_image_view_usage_create_info.html',1,'']]],
  ['vkinputattachmentaspectreference_329',['VkInputAttachmentAspectReference',['../struct_vk_input_attachment_aspect_reference.html',1,'']]],
  ['vkinstancecreateinfo_330',['VkInstanceCreateInfo',['../struct_vk_instance_create_info.html',1,'']]],
  ['vklayerproperties_331',['VkLayerProperties',['../struct_vk_layer_properties.html',1,'']]],
  ['vkmacossurfacecreateinfomvk_332',['VkMacOSSurfaceCreateInfoMVK',['../struct_vk_mac_o_s_surface_create_info_m_v_k.html',1,'']]],
  ['vkmappedmemoryrange_333',['VkMappedMemoryRange',['../struct_vk_mapped_memory_range.html',1,'']]],
  ['vkmemoryallocateflagsinfo_334',['VkMemoryAllocateFlagsInfo',['../struct_vk_memory_allocate_flags_info.html',1,'']]],
  ['vkmemoryallocateinfo_335',['VkMemoryAllocateInfo',['../struct_vk_memory_allocate_info.html',1,'']]],
  ['vkmemorybarrier_336',['VkMemoryBarrier',['../struct_vk_memory_barrier.html',1,'']]],
  ['vkmemorybarrier2_337',['VkMemoryBarrier2',['../struct_vk_memory_barrier2.html',1,'']]],
  ['vkmemorydedicatedallocateinfo_338',['VkMemoryDedicatedAllocateInfo',['../struct_vk_memory_dedicated_allocate_info.html',1,'']]],
  ['vkmemorydedicatedrequirements_339',['VkMemoryDedicatedRequirements',['../struct_vk_memory_dedicated_requirements.html',1,'']]],
  ['vkmemoryheap_340',['VkMemoryHeap',['../struct_vk_memory_heap.html',1,'']]],
  ['vkmemoryopaquecaptureaddressallocateinfo_341',['VkMemoryOpaqueCaptureAddressAllocateInfo',['../struct_vk_memory_opaque_capture_address_allocate_info.html',1,'']]],
  ['vkmemoryrequirements_342',['VkMemoryRequirements',['../struct_vk_memory_requirements.html',1,'']]],
  ['vkmemoryrequirements2_343',['VkMemoryRequirements2',['../struct_vk_memory_requirements2.html',1,'']]],
  ['vkmemorytype_344',['VkMemoryType',['../struct_vk_memory_type.html',1,'']]],
  ['vkmetalsurfacecreateinfoext_345',['VkMetalSurfaceCreateInfoEXT',['../struct_vk_metal_surface_create_info_e_x_t.html',1,'']]],
  ['vkoffset2d_346',['VkOffset2D',['../struct_vk_offset2_d.html',1,'']]],
  ['vkoffset3d_347',['VkOffset3D',['../struct_vk_offset3_d.html',1,'']]],
  ['vkphysicaldevice16bitstoragefeatures_348',['VkPhysicalDevice16BitStorageFeatures',['../struct_vk_physical_device16_bit_storage_features.html',1,'']]],
  ['vkphysicaldevice8bitstoragefeatures_349',['VkPhysicalDevice8BitStorageFeatures',['../struct_vk_physical_device8_bit_storage_features.html',1,'']]],
  ['vkphysicaldevicebufferdeviceaddressfeatures_350',['VkPhysicalDeviceBufferDeviceAddressFeatures',['../struct_vk_physical_device_buffer_device_address_features.html',1,'']]],
  ['vkphysicaldevicedepthstencilresolveproperties_351',['VkPhysicalDeviceDepthStencilResolveProperties',['../struct_vk_physical_device_depth_stencil_resolve_properties.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingfeatures_352',['VkPhysicalDeviceDescriptorIndexingFeatures',['../struct_vk_physical_device_descriptor_indexing_features.html',1,'']]],
  ['vkphysicaldevicedescriptorindexingproperties_353',['VkPhysicalDeviceDescriptorIndexingProperties',['../struct_vk_physical_device_descriptor_indexing_properties.html',1,'']]],
  ['vkphysicaldevicedriverproperties_354',['VkPhysicalDeviceDriverProperties',['../struct_vk_physical_device_driver_properties.html',1,'']]],
  ['vkphysicaldevicedynamicrenderingfeatures_355',['VkPhysicalDeviceDynamicRenderingFeatures',['../struct_vk_physical_device_dynamic_rendering_features.html',1,'']]],
  ['vkphysicaldeviceexternalbufferinfo_356',['VkPhysicalDeviceExternalBufferInfo',['../struct_vk_physical_device_external_buffer_info.html',1,'']]],
  ['vkphysicaldeviceexternalfenceinfo_357',['VkPhysicalDeviceExternalFenceInfo',['../struct_vk_physical_device_external_fence_info.html',1,'']]],
  ['vkphysicaldeviceexternalimageformatinfo_358',['VkPhysicalDeviceExternalImageFormatInfo',['../struct_vk_physical_device_external_image_format_info.html',1,'']]],
  ['vkphysicaldeviceexternalsemaphoreinfo_359',['VkPhysicalDeviceExternalSemaphoreInfo',['../struct_vk_physical_device_external_semaphore_info.html',1,'']]],
  ['vkphysicaldevicefeatures_360',['VkPhysicalDeviceFeatures',['../struct_vk_physical_device_features.html',1,'']]],
  ['vkphysicaldevicefeatures2_361',['VkPhysicalDeviceFeatures2',['../struct_vk_physical_device_features2.html',1,'']]],
  ['vkphysicaldevicefloatcontrolsproperties_362',['VkPhysicalDeviceFloatControlsProperties',['../struct_vk_physical_device_float_controls_properties.html',1,'']]],
  ['vkphysicaldevicegroupproperties_363',['VkPhysicalDeviceGroupProperties',['../struct_vk_physical_device_group_properties.html',1,'']]],
  ['vkphysicaldevicehostqueryresetfeatures_364',['VkPhysicalDeviceHostQueryResetFeatures',['../struct_vk_physical_device_host_query_reset_features.html',1,'']]],
  ['vkphysicaldeviceidproperties_365',['VkPhysicalDeviceIDProperties',['../struct_vk_physical_device_i_d_properties.html',1,'']]],
  ['vkphysicaldeviceimageformatinfo2_366',['VkPhysicalDeviceImageFormatInfo2',['../struct_vk_physical_device_image_format_info2.html',1,'']]],
  ['vkphysicaldeviceimagelessframebufferfeatures_367',['VkPhysicalDeviceImagelessFramebufferFeatures',['../struct_vk_physical_device_imageless_framebuffer_features.html',1,'']]],
  ['vkphysicaldeviceimagerobustnessfeatures_368',['VkPhysicalDeviceImageRobustnessFeatures',['../struct_vk_physical_device_image_robustness_features.html',1,'']]],
  ['vkphysicaldeviceinlineuniformblockfeatures_369',['VkPhysicalDeviceInlineUniformBlockFeatures',['../struct_vk_physical_device_inline_uniform_block_features.html',1,'']]],
  ['vkphysicaldeviceinlineuniformblockproperties_370',['VkPhysicalDeviceInlineUniformBlockProperties',['../struct_vk_physical_device_inline_uniform_block_properties.html',1,'']]],
  ['vkphysicaldevicelimits_371',['VkPhysicalDeviceLimits',['../struct_vk_physical_device_limits.html',1,'']]],
  ['vkphysicaldevicemaintenance3properties_372',['VkPhysicalDeviceMaintenance3Properties',['../struct_vk_physical_device_maintenance3_properties.html',1,'']]],
  ['vkphysicaldevicemaintenance4features_373',['VkPhysicalDeviceMaintenance4Features',['../struct_vk_physical_device_maintenance4_features.html',1,'']]],
  ['vkphysicaldevicemaintenance4properties_374',['VkPhysicalDeviceMaintenance4Properties',['../struct_vk_physical_device_maintenance4_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties_375',['VkPhysicalDeviceMemoryProperties',['../struct_vk_physical_device_memory_properties.html',1,'']]],
  ['vkphysicaldevicememoryproperties2_376',['VkPhysicalDeviceMemoryProperties2',['../struct_vk_physical_device_memory_properties2.html',1,'']]],
  ['vkphysicaldevicemultiviewfeatures_377',['VkPhysicalDeviceMultiviewFeatures',['../struct_vk_physical_device_multiview_features.html',1,'']]],
  ['vkphysicaldevicemultiviewproperties_378',['VkPhysicalDeviceMultiviewProperties',['../struct_vk_physical_device_multiview_properties.html',1,'']]],
  ['vkphysicaldevicepipelinecreationcachecontrolfeatures_379',['VkPhysicalDevicePipelineCreationCacheControlFeatures',['../struct_vk_physical_device_pipeline_creation_cache_control_features.html',1,'']]],
  ['vkphysicaldevicepointclippingproperties_380',['VkPhysicalDevicePointClippingProperties',['../struct_vk_physical_device_point_clipping_properties.html',1,'']]],
  ['vkphysicaldeviceprivatedatafeatures_381',['VkPhysicalDevicePrivateDataFeatures',['../struct_vk_physical_device_private_data_features.html',1,'']]],
  ['vkphysicaldeviceproperties_382',['VkPhysicalDeviceProperties',['../struct_vk_physical_device_properties.html',1,'']]],
  ['vkphysicaldeviceproperties2_383',['VkPhysicalDeviceProperties2',['../struct_vk_physical_device_properties2.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryfeatures_384',['VkPhysicalDeviceProtectedMemoryFeatures',['../struct_vk_physical_device_protected_memory_features.html',1,'']]],
  ['vkphysicaldeviceprotectedmemoryproperties_385',['VkPhysicalDeviceProtectedMemoryProperties',['../struct_vk_physical_device_protected_memory_properties.html',1,'']]],
  ['vkphysicaldevicesamplerfilterminmaxproperties_386',['VkPhysicalDeviceSamplerFilterMinmaxProperties',['../struct_vk_physical_device_sampler_filter_minmax_properties.html',1,'']]],
  ['vkphysicaldevicesamplerycbcrconversionfeatures_387',['VkPhysicalDeviceSamplerYcbcrConversionFeatures',['../struct_vk_physical_device_sampler_ycbcr_conversion_features.html',1,'']]],
  ['vkphysicaldevicescalarblocklayoutfeatures_388',['VkPhysicalDeviceScalarBlockLayoutFeatures',['../struct_vk_physical_device_scalar_block_layout_features.html',1,'']]],
  ['vkphysicaldeviceseparatedepthstencillayoutsfeatures_389',['VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures',['../struct_vk_physical_device_separate_depth_stencil_layouts_features.html',1,'']]],
  ['vkphysicaldeviceshaderatomicint64features_390',['VkPhysicalDeviceShaderAtomicInt64Features',['../struct_vk_physical_device_shader_atomic_int64_features.html',1,'']]],
  ['vkphysicaldeviceshaderdemotetohelperinvocationfeatures_391',['VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures',['../struct_vk_physical_device_shader_demote_to_helper_invocation_features.html',1,'']]],
  ['vkphysicaldeviceshaderdrawparametersfeatures_392',['VkPhysicalDeviceShaderDrawParametersFeatures',['../struct_vk_physical_device_shader_draw_parameters_features.html',1,'']]],
  ['vkphysicaldeviceshaderfloat16int8features_393',['VkPhysicalDeviceShaderFloat16Int8Features',['../struct_vk_physical_device_shader_float16_int8_features.html',1,'']]],
  ['vkphysicaldeviceshaderintegerdotproductfeatures_394',['VkPhysicalDeviceShaderIntegerDotProductFeatures',['../struct_vk_physical_device_shader_integer_dot_product_features.html',1,'']]],
  ['vkphysicaldeviceshaderintegerdotproductproperties_395',['VkPhysicalDeviceShaderIntegerDotProductProperties',['../struct_vk_physical_device_shader_integer_dot_product_properties.html',1,'']]],
  ['vkphysicaldeviceshadersubgroupextendedtypesfeatures_396',['VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures',['../struct_vk_physical_device_shader_subgroup_extended_types_features.html',1,'']]],
  ['vkphysicaldeviceshaderterminateinvocationfeatures_397',['VkPhysicalDeviceShaderTerminateInvocationFeatures',['../struct_vk_physical_device_shader_terminate_invocation_features.html',1,'']]],
  ['vkphysicaldevicesparseimageformatinfo2_398',['VkPhysicalDeviceSparseImageFormatInfo2',['../struct_vk_physical_device_sparse_image_format_info2.html',1,'']]],
  ['vkphysicaldevicesparseproperties_399',['VkPhysicalDeviceSparseProperties',['../struct_vk_physical_device_sparse_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupproperties_400',['VkPhysicalDeviceSubgroupProperties',['../struct_vk_physical_device_subgroup_properties.html',1,'']]],
  ['vkphysicaldevicesubgroupsizecontrolfeatures_401',['VkPhysicalDeviceSubgroupSizeControlFeatures',['../struct_vk_physical_device_subgroup_size_control_features.html',1,'']]],
  ['vkphysicaldevicesubgroupsizecontrolproperties_402',['VkPhysicalDeviceSubgroupSizeControlProperties',['../struct_vk_physical_device_subgroup_size_control_properties.html',1,'']]],
  ['vkphysicaldevicesynchronization2features_403',['VkPhysicalDeviceSynchronization2Features',['../struct_vk_physical_device_synchronization2_features.html',1,'']]],
  ['vkphysicaldevicetexelbufferalignmentproperties_404',['VkPhysicalDeviceTexelBufferAlignmentProperties',['../struct_vk_physical_device_texel_buffer_alignment_properties.html',1,'']]],
  ['vkphysicaldevicetexturecompressionastchdrfeatures_405',['VkPhysicalDeviceTextureCompressionASTCHDRFeatures',['../struct_vk_physical_device_texture_compression_a_s_t_c_h_d_r_features.html',1,'']]],
  ['vkphysicaldevicetimelinesemaphorefeatures_406',['VkPhysicalDeviceTimelineSemaphoreFeatures',['../struct_vk_physical_device_timeline_semaphore_features.html',1,'']]],
  ['vkphysicaldevicetimelinesemaphoreproperties_407',['VkPhysicalDeviceTimelineSemaphoreProperties',['../struct_vk_physical_device_timeline_semaphore_properties.html',1,'']]],
  ['vkphysicaldevicetoolproperties_408',['VkPhysicalDeviceToolProperties',['../struct_vk_physical_device_tool_properties.html',1,'']]],
  ['vkphysicaldeviceuniformbufferstandardlayoutfeatures_409',['VkPhysicalDeviceUniformBufferStandardLayoutFeatures',['../struct_vk_physical_device_uniform_buffer_standard_layout_features.html',1,'']]],
  ['vkphysicaldevicevariablepointersfeatures_410',['VkPhysicalDeviceVariablePointersFeatures',['../struct_vk_physical_device_variable_pointers_features.html',1,'']]],
  ['vkphysicaldevicevulkan11features_411',['VkPhysicalDeviceVulkan11Features',['../struct_vk_physical_device_vulkan11_features.html',1,'']]],
  ['vkphysicaldevicevulkan11properties_412',['VkPhysicalDeviceVulkan11Properties',['../struct_vk_physical_device_vulkan11_properties.html',1,'']]],
  ['vkphysicaldevicevulkan12features_413',['VkPhysicalDeviceVulkan12Features',['../struct_vk_physical_device_vulkan12_features.html',1,'']]],
  ['vkphysicaldevicevulkan12properties_414',['VkPhysicalDeviceVulkan12Properties',['../struct_vk_physical_device_vulkan12_properties.html',1,'']]],
  ['vkphysicaldevicevulkan13features_415',['VkPhysicalDeviceVulkan13Features',['../struct_vk_physical_device_vulkan13_features.html',1,'']]],
  ['vkphysicaldevicevulkan13properties_416',['VkPhysicalDeviceVulkan13Properties',['../struct_vk_physical_device_vulkan13_properties.html',1,'']]],
  ['vkphysicaldevicevulkanmemorymodelfeatures_417',['VkPhysicalDeviceVulkanMemoryModelFeatures',['../struct_vk_physical_device_vulkan_memory_model_features.html',1,'']]],
  ['vkphysicaldevicezeroinitializeworkgroupmemoryfeatures_418',['VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures',['../struct_vk_physical_device_zero_initialize_workgroup_memory_features.html',1,'']]],
  ['vkpipelinecachecreateinfo_419',['VkPipelineCacheCreateInfo',['../struct_vk_pipeline_cache_create_info.html',1,'']]],
  ['vkpipelinecacheheaderversionone_420',['VkPipelineCacheHeaderVersionOne',['../struct_vk_pipeline_cache_header_version_one.html',1,'']]],
  ['vkpipelinecolorblendattachmentstate_421',['VkPipelineColorBlendAttachmentState',['../struct_vk_pipeline_color_blend_attachment_state.html',1,'']]],
  ['vkpipelinecolorblendstatecreateinfo_422',['VkPipelineColorBlendStateCreateInfo',['../struct_vk_pipeline_color_blend_state_create_info.html',1,'']]],
  ['vkpipelinecreationfeedback_423',['VkPipelineCreationFeedback',['../struct_vk_pipeline_creation_feedback.html',1,'']]],
  ['vkpipelinecreationfeedbackcreateinfo_424',['VkPipelineCreationFeedbackCreateInfo',['../struct_vk_pipeline_creation_feedback_create_info.html',1,'']]],
  ['vkpipelinedepthstencilstatecreateinfo_425',['VkPipelineDepthStencilStateCreateInfo',['../struct_vk_pipeline_depth_stencil_state_create_info.html',1,'']]],
  ['vkpipelinedynamicstatecreateinfo_426',['VkPipelineDynamicStateCreateInfo',['../struct_vk_pipeline_dynamic_state_create_info.html',1,'']]],
  ['vkpipelineinputassemblystatecreateinfo_427',['VkPipelineInputAssemblyStateCreateInfo',['../struct_vk_pipeline_input_assembly_state_create_info.html',1,'']]],
  ['vkpipelinelayoutcreateinfo_428',['VkPipelineLayoutCreateInfo',['../struct_vk_pipeline_layout_create_info.html',1,'']]],
  ['vkpipelinemultisamplestatecreateinfo_429',['VkPipelineMultisampleStateCreateInfo',['../struct_vk_pipeline_multisample_state_create_info.html',1,'']]],
  ['vkpipelinerasterizationstatecreateinfo_430',['VkPipelineRasterizationStateCreateInfo',['../struct_vk_pipeline_rasterization_state_create_info.html',1,'']]],
  ['vkpipelinerenderingcreateinfo_431',['VkPipelineRenderingCreateInfo',['../struct_vk_pipeline_rendering_create_info.html',1,'']]],
  ['vkpipelineshaderstagecreateinfo_432',['VkPipelineShaderStageCreateInfo',['../struct_vk_pipeline_shader_stage_create_info.html',1,'']]],
  ['vkpipelineshaderstagerequiredsubgroupsizecreateinfo_433',['VkPipelineShaderStageRequiredSubgroupSizeCreateInfo',['../struct_vk_pipeline_shader_stage_required_subgroup_size_create_info.html',1,'']]],
  ['vkpipelinetessellationdomainoriginstatecreateinfo_434',['VkPipelineTessellationDomainOriginStateCreateInfo',['../struct_vk_pipeline_tessellation_domain_origin_state_create_info.html',1,'']]],
  ['vkpipelinetessellationstatecreateinfo_435',['VkPipelineTessellationStateCreateInfo',['../struct_vk_pipeline_tessellation_state_create_info.html',1,'']]],
  ['vkpipelinevertexinputstatecreateinfo_436',['VkPipelineVertexInputStateCreateInfo',['../struct_vk_pipeline_vertex_input_state_create_info.html',1,'']]],
  ['vkpipelineviewportstatecreateinfo_437',['VkPipelineViewportStateCreateInfo',['../struct_vk_pipeline_viewport_state_create_info.html',1,'']]],
  ['vkpresentinfokhr_438',['VkPresentInfoKHR',['../struct_vk_present_info_k_h_r.html',1,'']]],
  ['vkprivatedataslotcreateinfo_439',['VkPrivateDataSlotCreateInfo',['../struct_vk_private_data_slot_create_info.html',1,'']]],
  ['vkprotectedsubmitinfo_440',['VkProtectedSubmitInfo',['../struct_vk_protected_submit_info.html',1,'']]],
  ['vkpushconstantrange_441',['VkPushConstantRange',['../struct_vk_push_constant_range.html',1,'']]],
  ['vkquerypoolcreateinfo_442',['VkQueryPoolCreateInfo',['../struct_vk_query_pool_create_info.html',1,'']]],
  ['vkqueuefamilyproperties_443',['VkQueueFamilyProperties',['../struct_vk_queue_family_properties.html',1,'']]],
  ['vkqueuefamilyproperties2_444',['VkQueueFamilyProperties2',['../struct_vk_queue_family_properties2.html',1,'']]],
  ['vkrect2d_445',['VkRect2D',['../struct_vk_rect2_d.html',1,'']]],
  ['vkrenderingattachmentinfo_446',['VkRenderingAttachmentInfo',['../struct_vk_rendering_attachment_info.html',1,'']]],
  ['vkrenderinginfo_447',['VkRenderingInfo',['../struct_vk_rendering_info.html',1,'']]],
  ['vkrenderpassattachmentbegininfo_448',['VkRenderPassAttachmentBeginInfo',['../struct_vk_render_pass_attachment_begin_info.html',1,'']]],
  ['vkrenderpassbegininfo_449',['VkRenderPassBeginInfo',['../struct_vk_render_pass_begin_info.html',1,'']]],
  ['vkrenderpasscreateinfo_450',['VkRenderPassCreateInfo',['../struct_vk_render_pass_create_info.html',1,'']]],
  ['vkrenderpasscreateinfo2_451',['VkRenderPassCreateInfo2',['../struct_vk_render_pass_create_info2.html',1,'']]],
  ['vkrenderpassinputattachmentaspectcreateinfo_452',['VkRenderPassInputAttachmentAspectCreateInfo',['../struct_vk_render_pass_input_attachment_aspect_create_info.html',1,'']]],
  ['vkrenderpassmultiviewcreateinfo_453',['VkRenderPassMultiviewCreateInfo',['../struct_vk_render_pass_multiview_create_info.html',1,'']]],
  ['vkresolveimageinfo2_454',['VkResolveImageInfo2',['../struct_vk_resolve_image_info2.html',1,'']]],
  ['vksamplercreateinfo_455',['VkSamplerCreateInfo',['../struct_vk_sampler_create_info.html',1,'']]],
  ['vksamplerreductionmodecreateinfo_456',['VkSamplerReductionModeCreateInfo',['../struct_vk_sampler_reduction_mode_create_info.html',1,'']]],
  ['vksamplerycbcrconversioncreateinfo_457',['VkSamplerYcbcrConversionCreateInfo',['../struct_vk_sampler_ycbcr_conversion_create_info.html',1,'']]],
  ['vksamplerycbcrconversionimageformatproperties_458',['VkSamplerYcbcrConversionImageFormatProperties',['../struct_vk_sampler_ycbcr_conversion_image_format_properties.html',1,'']]],
  ['vksamplerycbcrconversioninfo_459',['VkSamplerYcbcrConversionInfo',['../struct_vk_sampler_ycbcr_conversion_info.html',1,'']]],
  ['vksemaphorecreateinfo_460',['VkSemaphoreCreateInfo',['../struct_vk_semaphore_create_info.html',1,'']]],
  ['vksemaphoresignalinfo_461',['VkSemaphoreSignalInfo',['../struct_vk_semaphore_signal_info.html',1,'']]],
  ['vksemaphoresubmitinfo_462',['VkSemaphoreSubmitInfo',['../struct_vk_semaphore_submit_info.html',1,'']]],
  ['vksemaphoretypecreateinfo_463',['VkSemaphoreTypeCreateInfo',['../struct_vk_semaphore_type_create_info.html',1,'']]],
  ['vksemaphorewaitinfo_464',['VkSemaphoreWaitInfo',['../struct_vk_semaphore_wait_info.html',1,'']]],
  ['vkshadermodulecreateinfo_465',['VkShaderModuleCreateInfo',['../struct_vk_shader_module_create_info.html',1,'']]],
  ['vksparsebuffermemorybindinfo_466',['VkSparseBufferMemoryBindInfo',['../struct_vk_sparse_buffer_memory_bind_info.html',1,'']]],
  ['vksparseimageformatproperties_467',['VkSparseImageFormatProperties',['../struct_vk_sparse_image_format_properties.html',1,'']]],
  ['vksparseimageformatproperties2_468',['VkSparseImageFormatProperties2',['../struct_vk_sparse_image_format_properties2.html',1,'']]],
  ['vksparseimagememorybind_469',['VkSparseImageMemoryBind',['../struct_vk_sparse_image_memory_bind.html',1,'']]],
  ['vksparseimagememorybindinfo_470',['VkSparseImageMemoryBindInfo',['../struct_vk_sparse_image_memory_bind_info.html',1,'']]],
  ['vksparseimagememoryrequirements_471',['VkSparseImageMemoryRequirements',['../struct_vk_sparse_image_memory_requirements.html',1,'']]],
  ['vksparseimagememoryrequirements2_472',['VkSparseImageMemoryRequirements2',['../struct_vk_sparse_image_memory_requirements2.html',1,'']]],
  ['vksparseimageopaquememorybindinfo_473',['VkSparseImageOpaqueMemoryBindInfo',['../struct_vk_sparse_image_opaque_memory_bind_info.html',1,'']]],
  ['vksparsememorybind_474',['VkSparseMemoryBind',['../struct_vk_sparse_memory_bind.html',1,'']]],
  ['vkspecializationinfo_475',['VkSpecializationInfo',['../struct_vk_specialization_info.html',1,'']]],
  ['vkspecializationmapentry_476',['VkSpecializationMapEntry',['../struct_vk_specialization_map_entry.html',1,'']]],
  ['vkstencilopstate_477',['VkStencilOpState',['../struct_vk_stencil_op_state.html',1,'']]],
  ['vksubmitinfo_478',['VkSubmitInfo',['../struct_vk_submit_info.html',1,'']]],
  ['vksubmitinfo2_479',['VkSubmitInfo2',['../struct_vk_submit_info2.html',1,'']]],
  ['vksubpassbegininfo_480',['VkSubpassBeginInfo',['../struct_vk_subpass_begin_info.html',1,'']]],
  ['vksubpassdependency_481',['VkSubpassDependency',['../struct_vk_subpass_dependency.html',1,'']]],
  ['vksubpassdependency2_482',['VkSubpassDependency2',['../struct_vk_subpass_dependency2.html',1,'']]],
  ['vksubpassdescription_483',['VkSubpassDescription',['../struct_vk_subpass_description.html',1,'']]],
  ['vksubpassdescription2_484',['VkSubpassDescription2',['../struct_vk_subpass_description2.html',1,'']]],
  ['vksubpassdescriptiondepthstencilresolve_485',['VkSubpassDescriptionDepthStencilResolve',['../struct_vk_subpass_description_depth_stencil_resolve.html',1,'']]],
  ['vksubpassendinfo_486',['VkSubpassEndInfo',['../struct_vk_subpass_end_info.html',1,'']]],
  ['vksubresourcelayout_487',['VkSubresourceLayout',['../struct_vk_subresource_layout.html',1,'']]],
  ['vksurfacecapabilitieskhr_488',['VkSurfaceCapabilitiesKHR',['../struct_vk_surface_capabilities_k_h_r.html',1,'']]],
  ['vksurfaceformatkhr_489',['VkSurfaceFormatKHR',['../struct_vk_surface_format_k_h_r.html',1,'']]],
  ['vkswapchaincreateinfokhr_490',['VkSwapchainCreateInfoKHR',['../struct_vk_swapchain_create_info_k_h_r.html',1,'']]],
  ['vktimelinesemaphoresubmitinfo_491',['VkTimelineSemaphoreSubmitInfo',['../struct_vk_timeline_semaphore_submit_info.html',1,'']]],
  ['vkvertexinputattributedescription_492',['VkVertexInputAttributeDescription',['../struct_vk_vertex_input_attribute_description.html',1,'']]],
  ['vkvertexinputbindingdescription_493',['VkVertexInputBindingDescription',['../struct_vk_vertex_input_binding_description.html',1,'']]],
  ['vkviewport_494',['VkViewport',['../struct_vk_viewport.html',1,'']]],
  ['vkwaylandsurfacecreateinfokhr_495',['VkWaylandSurfaceCreateInfoKHR',['../struct_vk_wayland_surface_create_info_k_h_r.html',1,'']]],
  ['vkwin32surfacecreateinfokhr_496',['VkWin32SurfaceCreateInfoKHR',['../struct_vk_win32_surface_create_info_k_h_r.html',1,'']]],
  ['vkwritedescriptorset_497',['VkWriteDescriptorSet',['../struct_vk_write_descriptor_set.html',1,'']]],
  ['vkwritedescriptorsetinlineuniformblock_498',['VkWriteDescriptorSetInlineUniformBlock',['../struct_vk_write_descriptor_set_inline_uniform_block.html',1,'']]],
  ['vkxcbsurfacecreateinfokhr_499',['VkXcbSurfaceCreateInfoKHR',['../struct_vk_xcb_surface_create_info_k_h_r.html',1,'']]],
  ['vkxlibsurfacecreateinfokhr_500',['VkXlibSurfaceCreateInfoKHR',['../struct_vk_xlib_surface_create_info_k_h_r.html',1,'']]],
  ['volume_501',['Volume',['../classluisa_1_1compute_1_1_volume.html',1,'luisa::compute']]],
  ['volume_5felement_5fimpl_502',['volume_element_impl',['../structluisa_1_1compute_1_1detail_1_1volume__element__impl.html',1,'luisa::compute::detail']]],
  ['volume_5felement_5fimpl_3c_20std_3a_3aremove_5fcvref_5ft_3c_20volumeorview_20_3e_20_3e_503',['volume_element_impl&lt; std::remove_cvref_t&lt; VolumeOrView &gt; &gt;',['../structluisa_1_1compute_1_1detail_1_1volume__element__impl.html',1,'luisa::compute::detail']]],
  ['volume_5felement_5fimpl_3c_20volume_3c_20t_20_3e_20_3e_504',['volume_element_impl&lt; Volume&lt; T &gt; &gt;',['../structluisa_1_1compute_1_1detail_1_1volume__element__impl_3_01_volume_3_01_t_01_4_01_4.html',1,'luisa::compute::detail']]],
  ['volume_5felement_5fimpl_3c_20volumeview_3c_20t_20_3e_20_3e_505',['volume_element_impl&lt; VolumeView&lt; T &gt; &gt;',['../structluisa_1_1compute_1_1detail_1_1volume__element__impl_3_01_volume_view_3_01_t_01_4_01_4.html',1,'luisa::compute::detail']]],
  ['volumeexprproxy_506',['VolumeExprProxy',['../classluisa_1_1compute_1_1detail_1_1_volume_expr_proxy.html',1,'luisa::compute::detail']]],
  ['volumeview_507',['VolumeView',['../classluisa_1_1compute_1_1_volume_view.html',1,'luisa::compute']]],
  ['vprintf_5fargs_508',['vprintf_args',['../structvprintf__args.html',1,'']]],
  ['vtable_509',['vtable',['../structmove__only__function__detail_1_1__callable__trait_1_1vtable.html',1,'move_only_function_detail::_callable_trait']]]
];
