includes("EASTL/xmake.lua")
includes("glfw/xmake.lua")
includes("imgui/xmake.lua")
includes("application/xmake.lua")
includes("base_classes/xmake.lua")
includes("core/xmake.lua")
includes("engine/xmake.lua")
includes("math/xmake.lua")
includes("render_core/xmake.lua")
includes("memory/xmake.lua")
includes("spdlog/xmake.lua")
includes("utility/xmake.lua")
includes("gui/xmake.lua")
includes("dsl/xmake.lua")
includes("ast/xmake.lua")
includes("backends/xmake.lua")
includes("runtime/xmake.lua")
includes("vstl/xmake.lua")
includes("liblmdb/xmake.lua")
includes("base/xmake.lua")
includes("sdl/xmake.lua")
includes("util/xmake.lua")
includes("oidn/xmake.lua")
includes("zlib/xmake.lua")
includes("tinyexr/xmake.lua")
includes("stb/xmake.lua")
includes("magic_enum/xmake.lua")
includes("reflect-cpp/xmake.lua")
table.insert(global_headerfiles, "runtime/**.h")
table.insert(global_headerfiles, "runtime/**.hpp")
table.insert(global_defines, "LUISA_ENABLE_DSL=1")