var dir_045759be54b861687a7aabd2f84cecd8 =
[
    [ "includes.h", "includes_8h.html", "includes_8h" ],
    [ "main.cpp", "spdlog_2tests_2main_8cpp.html", null ],
    [ "test_async.cpp", "test__async_8cpp.html", "test__async_8cpp" ],
    [ "test_backtrace.cpp", "test__backtrace_8cpp.html", "test__backtrace_8cpp" ],
    [ "test_bin_to_hex.cpp", "test__bin__to__hex_8cpp.html", "test__bin__to__hex_8cpp" ],
    [ "test_cfg.cpp", "test__cfg_8cpp.html", "test__cfg_8cpp" ],
    [ "test_circular_q.cpp", "test__circular__q_8cpp.html", "test__circular__q_8cpp" ],
    [ "test_create_dir.cpp", "test__create__dir_8cpp.html", "test__create__dir_8cpp" ],
    [ "test_custom_callbacks.cpp", "test__custom__callbacks_8cpp.html", "test__custom__callbacks_8cpp" ],
    [ "test_daily_logger.cpp", "test__daily__logger_8cpp.html", "test__daily__logger_8cpp" ],
    [ "test_dup_filter.cpp", "test__dup__filter_8cpp.html", "test__dup__filter_8cpp" ],
    [ "test_errors.cpp", "test__errors_8cpp.html", "test__errors_8cpp" ],
    [ "test_eventlog.cpp", "test__eventlog_8cpp.html", null ],
    [ "test_file_helper.cpp", "test__file__helper_8cpp.html", "test__file__helper_8cpp" ],
    [ "test_file_logging.cpp", "test__file__logging_8cpp.html", "test__file__logging_8cpp" ],
    [ "test_fmt_helper.cpp", "test__fmt__helper_8cpp.html", "test__fmt__helper_8cpp" ],
    [ "test_macros.cpp", "test__macros_8cpp.html", "test__macros_8cpp" ],
    [ "test_misc.cpp", "test__misc_8cpp.html", "test__misc_8cpp" ],
    [ "test_mpmc_q.cpp", "test__mpmc__q_8cpp.html", "test__mpmc__q_8cpp" ],
    [ "test_pattern_formatter.cpp", "test__pattern__formatter_8cpp.html", "test__pattern__formatter_8cpp" ],
    [ "test_registry.cpp", "test__registry_8cpp.html", "test__registry_8cpp" ],
    [ "test_sink.h", "test__sink_8h.html", "test__sink_8h" ],
    [ "test_stdout_api.cpp", "test__stdout__api_8cpp.html", "test__stdout__api_8cpp" ],
    [ "test_stopwatch.cpp", "test__stopwatch_8cpp.html", "test__stopwatch_8cpp" ],
    [ "test_systemd.cpp", "test__systemd_8cpp.html", "test__systemd_8cpp" ],
    [ "test_time_point.cpp", "test__time__point_8cpp.html", "test__time__point_8cpp" ],
    [ "utils.cpp", "utils_8cpp.html", "utils_8cpp" ],
    [ "utils.h", "tests_2utils_8h.html", "tests_2utils_8h" ]
];