var dir_fedc5c195628998e7d79c31476661589 =
[
    [ "prim", "dir_d64908bae465b754afd79e51ffb7c7ab.html", "dir_d64908bae465b754afd79e51ffb7c7ab" ],
    [ "alloc-aligned.c", "alloc-aligned_8c.html", "alloc-aligned_8c" ],
    [ "alloc-override.c", "alloc-override_8c.html", null ],
    [ "alloc-posix.c", "alloc-posix_8c.html", "alloc-posix_8c" ],
    [ "alloc.c", "alloc_8c.html", "alloc_8c" ],
    [ "arena-meta.c", "arena-meta_8c.html", "arena-meta_8c" ],
    [ "arena.c", "arena_8c.html", "arena_8c" ],
    [ "bitmap.c", "bitmap_8c.html", "bitmap_8c" ],
    [ "bitmap.h", "bitmap_8h.html", "bitmap_8h" ],
    [ "build.mimalloc.cpp", "build_8mimalloc_8cpp.html", null ],
    [ "free.c", "free_8c.html", "free_8c" ],
    [ "heap.c", "heap_8c.html", "heap_8c" ],
    [ "init.c", "_e_a_s_t_l_2packages_2mimalloc_2src_2init_8c.html", "_e_a_s_t_l_2packages_2mimalloc_2src_2init_8c" ],
    [ "libc.c", "libc_8c.html", "libc_8c" ],
    [ "options.c", "options_8c.html", "options_8c" ],
    [ "os.c", "os_8c.html", "os_8c" ],
    [ "page-map.c", "page-map_8c.html", "page-map_8c" ],
    [ "page-queue.c", "page-queue_8c.html", "page-queue_8c" ],
    [ "page.c", "page_8c.html", "page_8c" ],
    [ "random.c", "random_8c.html", "random_8c" ],
    [ "static.c", "static_8c.html", "static_8c" ],
    [ "stats.c", "stats_8c.html", "stats_8c" ]
];