target("asset")
    set_group("module")
    set_kind("$(kind)")
    add_includedirs("./", { public = true })
    add_includedirs("$(projectdir)/external/taskflow/3rd-party")
    add_headerfiles("asset_module.h")
    add_files("asset_module.cpp")
    add_deps("reflect-cpp", "spdlog")
target_end()

table.insert(global_deps, "asset")