table.insert(global_includedirs, "runtime/imgui")
table.insert(global_includedirs, "runtime/backends")

table.insert(global_files, "runtime/imgui/imgui.cpp")
table.insert(global_files, "runtime/imgui/imgui_draw.cpp")
table.insert(global_files, "runtime/imgui/imgui_widgets.cpp")
table.insert(global_files, "runtime/imgui/imgui_tables.cpp")
table.insert(global_files, "runtime/imgui/backends/imgui_impl_dx12.cpp")
table.insert(global_files, "runtime/imgui/backends/imgui_impl_glfw.cpp")
table.insert(global_files, "runtime/imgui/backends/imgui_impl_vulkan.cpp")
