target("core")
    set_group("runtime")
    set_kind("$(kind)")
    add_includedirs("./", { public = true })
    add_headerfiles("./*.h")
    add_files("./*.cpp")
    add_deps("windows")
target_end()

table.insert(global_deps, "core")